import json
import os
import argparse

# Change directory to project root
abspath = os.path.abspath(__file__)
dname = os.path.dirname(abspath)
os.chdir(f'{dname}/../')
print(dname)

#
# Set up Argument Parser for processing command line arguments
#
parser = argparse.ArgumentParser(description='Extract environment variables for given image.')
parser.add_argument('-si','--sagemaker_image_name', type=str, help='Docker image name (same as directory) to retrieve ECR repo from tf output')
args = parser.parse_args()

print(args.sagemaker_image_name)

# Assumes script is called from root of project
with open('./infrastructure/out.json', 'r') as f:
    terraform_output = json.load(f)

sagemaker_out = terraform_output['sagemaker']['value']

# Write env vars to .env file in root directory.
with open(f'.env', 'w') as output:
    output.write(
f""" # Generated by script
export REGION="{sagemaker_out['domain_region']}"
export ECR_REPO="{sagemaker_out['custom_image_ecr_repository_urls'].get(args.sagemaker_image_name, "")}"
export SAGEMAKER_DOMAIN_ID="{sagemaker_out['domain_id']}"
export SAGEMAKER_EXECUTION_ROLE_ARN="{sagemaker_out['execution_role_arn']}"
export ACCOUNT_ID="{terraform_output['account_id']['value']}"
"""
    )